### ISSUE TITLE
Elaborate more about "Swift coalescing operator"

### ISSUE THREAD

**Issue by onmyway133** [objcio/functional-programming-in-swift#27]
On page 94,

```
func ??<T>(optional: T?, defaultValue: T) -> T {
    if let x = optional {
        return x
    } else {
        return defaultValue
    }
}
```

You said that
> There is one problem with this definition: the defaultValue may be evaluated, regardless of whether or not the optional is nil

Can you elaborate more, what do you mean by "the defaultValue may be evaluated" ?

**Comment by refried** [comment]
A bit late to the party here, but maybe you want to say that in the original, the expression passed to defaultValue will be evaluated before `??` is even called.  "may be evaluated" is pretty ambiguous.  It will definitely be evaluated.  

The expensive operation occurs before `??`, and we're passed a value or reference, returning that value is not expensive, so that's why @onmyway133 is reasonably confused.

`defaultValue: T` is a value, not a computation (huge or otherwise).  You want to change it to accept a computation instead of a value, so that you can decide internally whether or not to execute it.

**Comment by chriseidhof** [comment]
Thanks, this has been really good feedback. We've changed the wording and will update this in the next version of the book.
