### ISSUE TITLE
Core Image Wrapper URL Playground Problems

### ISSUE THREAD

**Issue by jarsen** [objcio/functional-programming-in-swift#41]
I'm having problems getting the code for Chapter 3 to work, both on my own and in the playground. On line 57 I'm getting crashes. Is this a playground or framework bug? Or am I doing something wrong?

![screen shot 2014-11-10 at 8 07 47 am](https://cloud.githubusercontent.com/assets/73101/4977937/94444eee-68eb-11e4-965a-d8abae6bb2a9.png)

In my own playground the error I get is this:
`ImageIO: CGImageSourceCreateWithURL CFURLCreateDataAndPropertiesFromResource failed with error code -14.`

**Comment by carlosypunto** [comment]
No longer works in the playgrounds, would not be easier than you deploy the OS X project? For example, iOS developers may not know how to do it and not be able to prove it. I think it is your responsibility that the issue is sufficiently clear. I do not think cost much. Generally what most miss is running code
