### ISSUE TITLE
QuickCheck: confusing sentence

### ISSUE THREAD

**Issue by ole** [objcio/functional-programming-in-swift#84]
> In principle, the user could try to trim the input that triggered the failure and attempt rerunning the test — rather than place the burden on the user — however, we will automate this process.

I don’t think the "rather than place the burden on the user" makes sense at that position in the sentence. It seems this piece should be positioned at the end of the sentence or removed completely.

![img_0332](https://cloud.githubusercontent.com/assets/5010/7429005/1e4ec728-effa-11e4-8042-fad9a46cac3d.PNG)

**Comment by deutschbitte** [comment]
@ole  What you've suggested (moving it to the end) is clear, but how it is now is also clear (though it may strike you as awkward, it's still correct). I don't have any problems with changing it though. Whatever the others think. If changed, then it should be:

In principle, the user could try to trim the input that triggered the failure and attempt rerunning the test. However, we will automate this process, rather than place the burden on the user.
